### ISSUE TITLE
It doesn't work with serverless 1.53.0

### ISSUE THREAD

**Issue by UshakovRuslan** [janders223/serverless-offline-ssm#21]
Hi @janders223 
it seems like it doesn't work with the new version of serverless (now it's v1.53.0). 
But it works with the older version, for instance with v1.50.1

v1.53.0
![with-serverless-1 53 0](https://user-images.githubusercontent.com/48594656/66109818-28ad9900-e5ce-11e9-935e-60172e668a63.png)

v.1.50.1
![with-serverless-1 50 1](https://user-images.githubusercontent.com/48594656/66109835-306d3d80-e5ce-11e9-8acd-5197327abae6.png)

**Comment by janders223** [comment]
My apologies, I have been out of town on vacation without internet access. I will look into this issue.

**Comment by barendb** [comment]
@UshakovRuslan I've created a PR to fix the Serverless compatibility feel free test if you can
https://github.com/janders223/serverless-offline-ssm/pull/22

**Comment by janders223** [comment]
@barendb Thank you so much! My apologies for not getting to this, things have been a little crazy lately.

**Comment by Maxwell2022** [comment]
@janders223 any chance to get this released in NPM?

**Comment by ushakov-ruslan** [comment]
Thanks guys for the updates!
