### ISSUE TITLE
[Error] serverless invoke local

### ISSUE THREAD

**Issue by Maxwell2022** [janders223/serverless-offline-ssm#23]
Using the version `4.0` with serverless `1.55` it's working fine running my server offline, however trying to invoke a function locally it fails with promises timeout.

![image](https://user-images.githubusercontent.com/670701/67920233-95c94400-fbf7-11e9-8a66-75e6d2475cc2.png)

Again, starting the server offline work great:

```
node --nolazy node_modules/.bin/serverless offline start --webpack-use-polling --stage development
```

That's my plugins:

```
plugins:
  - serverless-offline-ssm
  - serverless-offline
  - serverless-webpack
  - serverless-plugin-tracing
  - serverless-domain-manager
  - serverless-api-compression
```

**Comment by AlejandroGalAtSportBLX** [comment]
@janders223 My project uses `serverless invoke local` , Will this plugin work?

**Comment by janders223** [comment]
Not currently no. I need to update it to also work with that command.

**Comment by Maxwell2022** [comment]
> The plugin is designed to only running when calling `serverless offline` and was never originally intended to be used with the `invoke` command. I actually hadn't thought of this use case prior to now, but can see the usefulness for local testing of non HTTP lambdas.
> 
> It should be fairly easy to add another check in the early return based on the commands passed in if you are open to submitting a pull request.

I'm not really familiar with how serverless plugins work but I can have a look

**Comment by Maxwell2022** [comment]
Here is my PR it looks like it's working fine :)

https://github.com/janders223/serverless-offline-ssm/pull/24

**Comment by janders223** [comment]
@AlejandroGalAtSportBLX The latest updated version 4.1.0 now supports using this plugin with invoke local.
