### ISSUE TITLE
Watch changes in .env

### ISSUE THREAD

**Issue by DimaDK24** [janders223/serverless-offline-ssm#25]
Is it possible to get new content from `.env` file on-the-fly, without reloading serverless-offline server?

It would be a nice feature :)

Sometimes developers can forget that update to `.env` requires reloading serverless-offline and they will need to debug, why something that is dependent on `.env` data doesn't work

**Comment by janders223** [comment]
Unfortunately the way that the serverless framework loads the variables, it requires a full restart of the server.

**Comment by DimaDK24** [comment]
Oh, okay, thanks for clarification
