### ISSUE TITLE
Not Working as Instructed

### ISSUE THREAD

**Issue by paulcruseSG** [janders223/serverless-offline-ssm#4]
Can you add an example of how this should be used in the serverless file?

Currently a snippet of my file looks like this:

```
plugins:
    - serverless-python-requirements
    - serverless-aws-documentation
    - serverless-offline-ssm
    - serverless-offline-python
    - serverless-offline

functions:
    BASE_URL: ${ssm:/service/base_url}
```

Then in my `.env` (stored at the same level as my serverless.yml file) I have:
```
BASE_URL = https://some.api.com/url
```

When I use this format I get this error:

```
Serverless Warning --------------------------------------

  ################################################################################


 Serverless Warning --------------------------------------

  # 2502: 0 of 1 promises have settled


 Serverless Warning --------------------------------------

  # 2502: 1 unsettled promises:


 Serverless Warning --------------------------------------

  # 2502:   ssm:/service/base_url waited on by: ${ssm:/service/base_url}


 Serverless Warning --------------------------------------

  ################################################################################


  Serverless Error ---------------------------------------

  AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.27.3
````

**Comment by janders223** [comment]
@paulcruseSG I've not seen that error code before. It seems to me that the `serverless-offline-python` plugin is just a dead fork of the original `serverless-offline` plugin. The way `serverless-offline` starts up, could be causing weird issues in the serverless plugin load path.

**Comment by paulcruseSG** [comment]
@janders223 ok I'll look at removing the `serverless-offline-python` plugin from my dev environment.

Is my current implementation (barring the error) correct? Like I do I have the variable in the right order and the `.env` file in the correct format? Do you have a working exampled I can source?

**Comment by janders223** [comment]
@paulcruseSG Outside of the possibility of conflicting plugins, everything else looks correct.
