### ISSUE TITLE
Support for AWS Secrets Manager object values

### ISSUE THREAD

**Issue by devakone** [janders223/serverless-offline-ssm#58]
HI! Thanks for a great plugin.
I am currently trying to use this to provide credentials that will be retrieved from AWS Secrets Manager in production and in the Serverless SSM documentation, it states that

`Variables can also be object, since AWS Secrets Manager can store secrets not only in plain text but also in JSON.`

it looks like this plugin assumes that all the secrets that will be retrieved will be plain text.

Can you confirm that the plugin does not support AWS Secrets Manager object type values?

**Comment by janders223** [comment]
This should be working in version 5.1.0
